language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=django_mfa_rest  test_runner.py test

after_success:
  coveralls
